baseURL = 'https://owneroperators.online/'
languageCode = 'en-US'
title = 'Owner Operators'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Songs'
    pageRef = '/songs'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[[params.social]]
  name = "GitHub"
  url = "https://github.com/owneroperators"

[[params.social]]
  name = "Bandcamp"
  url = "https://owneroperators.bandcamp.com/"

[[params.social]]
  name = "Instagram"
  url = "https://www.instagram.com/owneroperators.mp4"